#!/bin/bash
#
# Script to rename libvmod-example into libvmod-foo.
# (where "foo" is your new vmod name, of course.)
#
# Leaves the changes uncommitted in the working tree, so you get to fix any
# unintended changes.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, September 2014.
#
set -o errexit

NAME=$1
if [ -z "$NAME" ]; then
	echo "Usage: $0 <new-vmod-name-without-libvmod-prefix>"
	echo "Rename libvmod-example source tree."
	echo
	exit -1
fi

if ! git diff-index --quiet HEAD --; then
	echo "ERROR: Need a clean working tree. Run \"git stash\" first."
	exit -2
fi

git mv src/vmod_example.c src/vmod_${NAME}.c
git mv src/vmod_example.vcc src/vmod_${NAME}.vcc
git mv vmod-example.spec vmod-${NAME}.spec

git grep -z -l example | xargs -0 sed -i -s -e "s/example/${NAME}/g"

git rm rename-vmod-script

echo "All done."
echo -e "For your cut&paste needs:\n  git commit -a -m \"Automatic rename of libvmod-example to libvmod-${NAME}.\""



